### ISSUE TITLE
No full screen

### ISSUE THREAD

**Issue by craigleat** [marvindanig/The-Solar-System#2]
Using chrome on android I cannot enter full screen mode. It would be nice to use the screen space occupied by the address bar and status bar - see the screen shot.

![screenshot_2015-12-11-09-13-47](https://cloud.githubusercontent.com/assets/12593105/11738286/10288ec2-9fea-11e5-963d-e90a94559f96.png)

**Comment by marvindanig** [comment]
Implementing [full screen](http://caniuse.com/#feat=fullscreen) API is certainly on my #to-do list; I hope to get to it soon enough.
